// This file was generated by src/cmd/generate-error-map
// based on docs/openapi.yaml & src/cmd/generate-error-map/schema-http-code.json.
// Please DON'T change this file directly!!!
// Apply your changes in docs/openapi.yaml & src/cmd/generate-error-map/schema-http-code.json
// and run `npm run generate-error-map` instead.
export const ErrorCodes = {
    API_VALIDATION_ERROR: 'API_VALIDATION_ERROR',
    REQUEST_FORBIDDEN_ERROR: 'REQUEST_FORBIDDEN_ERROR',
    UNAUTHORIZED_ERROR: 'UNAUTHORIZED_ERROR',
    AUTH_REJECTED: 'AUTH_REJECTED',
    INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR'
};

export const ErrorCodeMap: { [key: string]: number } = {
    API_VALIDATION_ERROR: 400,
    UNAUTHORIZED_ERROR: 401,
    REQUEST_FORBIDDEN_ERROR: 403,
    AUTH_REJECTED: 404,
    INTERNAL_SERVER_ERROR: 500
};
